# Change these first
owner: zhujunyong # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Advocacy Hub
    url: https://www.ibm.com/community/z/advocacy/
    icon: https://www.ibm.com/favicon.ico
  - name: Community Node-RED
    url: https://www.ibm.com/community/z/api/node/community/public
    icon: https://www.ibm.com/favicon.ico
    headers: 
      - "Authorization: Basic $SECRET_COMMUNITY_NODE_RED"
      - "Content-Type: text/plain"
    __dangerous__body_down_if_text_missing: 9476eac0-4605-4c10-906d-01a95923ae0b
  - name: Fans of Z (HL) Group page
    url: https://community.ibm.com/community/user/ibmz-and-linuxone/groups/group-home?CommunityKey=b8b88f20-24c8-49f0-9021-4a8c6247a067
    icon: https://www.ibm.com/favicon.ico
    __dangerous__body_down_if_text_missing: "Login or register"
  - name: Middleware Aggregation API
    url: https://www.ibm.com/community/z/api/cmt/getContentAggregation
    icon: https://www.ibm.com/favicon.ico
    method: POST
    headers: 
      - "Authorization: Basic $SECRET_MIDDLEWARE_AGGREGATION_API"
      - "Content-Type: application/json"
    body: '{ "tag": "IBM Z", "limit": 1 }'
    __dangerous__body_down_if_text_missing: '"blogs":['
    # __dangerous__body_down_if_text_missing: '"blogs": [' # need to confirm the content
  - name: T90 (WP) Home page
    url: https://www.ibm.com/community/z-and-cloud/
    icon: https://www.ibm.com/favicon.ico
    __dangerous__body_down_if_text_missing: 'Contact an expert'
  - name: T90 (WP) Japanese home page
    url: https://www.ibm.com/community/z-and-cloud/ja/
    icon: https://www.ibm.com/favicon.ico
    __dangerous__body_down_if_text_missing: 'IBMエキスパートにコンタクト'
  - name: Z Community (WP) Home page
    url: https://www.ibm.com/community/z
    icon: https://www.ibm.com/favicon.ico
    # __dangerous__body_down_if_text_missing: 'Join the new IBM Z and LinuxONE Community'
    __dangerous__body_down_if_text_missing: 'IBM Z and LinuxONE Community'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
